SELECT log FROM TABLE(USER$KELLER.PUBLIC.SPCS_APP_BUILDER_JOB_01C78C16030B3D010000EB9D0AAF6E8A!SPCS_GET_LOGS())
WHERE log ILIKE ANY ('%error%', '%ETIMEDOUT%', '%ECONN%', '%INSTALL%') ORDER BY timestamp;
