CREATE DATABASE IF NOT EXISTS NPM_PL;
CREATE SCHEMA IF NOT EXISTS NPM_PL.T;
CREATE OR REPLACE NETWORK RULE NPM_PL.T.PRIVATE_NPM_RULE MODE=EGRESS TYPE=PRIVATE_HOST_PORT VALUE_LIST=('npm.kk-private.internal:80');
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION PRIVATE_NPM_EAI ALLOWED_NETWORK_RULES=(NPM_PL.T.PRIVATE_NPM_RULE) ENABLED=TRUE;
CREATE IMAGE REPOSITORY IF NOT EXISTS NPM_PL.T.IMAGES;
CREATE COMPUTE POOL IF NOT EXISTS NPM_PL_POOL MIN_NODES=1 MAX_NODES=1 INSTANCE_FAMILY=CPU_X64_XS AUTO_SUSPEND_SECS=600;
SELECT SYSTEM$GET_PRIVATELINK_ENDPOINTS_INFO();
SHOW IMAGE REPOSITORIES IN SCHEMA NPM_PL.T;
